[tool.black]
line-length = 160
target-version = ["py311"]

[tool.ruff]
line-length = 160
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]  # E: pycodestyle, F: pyflakes, I: import sorting (isort)
ignore = ["E203"]         # black-compatible

[tool.ruff.lint.per-file-ignores]
"gui/main_window.py" = ["E701", "E702"]
"tests/*.py" = ["E402"]
